### PR TITLE
RequestAuthorizer for IndexHttp

### PR DESCRIPTION
**Pull request by audax**
stub and simple and the BoxClient is also a RequestAuthorizer

### CODE REVIEW

**Comment by enkore** [comment]
Another puzzle piece: https://github.com/Qabel/qabel-core/tree/m/indexauth

**Comment by julianseeger** [comment]
if you two both think it fits, feel free to merge. Code looks good.

**Comment by enkore** [comment]
*plopp*

**Comment by julianseeger** [comment]
>@audax added the research label 18 days ago

done with research?

**Pull request merged**
