### PR TITLE
Replaced Bouncy Castle with Spongy Castle

### PR DESCRIPTION
**Pull request by L-Henke**
Notice: This PR goes into the new spongycastle branch and not into the master.

### CODE REVIEW

**Comment by jasinai** [comment]
I think there are three ways to handle failing builds on travis
* change the language to android for the branch
* [blacklist the branch from building](http://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches)
* remove the .travis.yml and choose the option `Build only if .travis.yml is present`

Otherwise: :+1: for merge

**Comment by thechauffeur** [comment]
Please let us talk about how to handle this on Monday.

**Comment by jan-schreib** [comment]
Anything new on this?

**Comment by roeslpa** [comment]
I guess this PR is obsolete now?!

**Comment by audax** [comment]
Yes.

**Pull request closed without merging**
