### PR TITLE
Spongycastle integration

### PR DESCRIPTION
**Pull request by roeslpa**
Removed all bouncycastle dependencies by using spongycastle. The spongycastle API is used directly, not via jce provider. Solves issue #413 .

### CODE REVIEW

**Comment by audax** [comment]
You changed the indentation from tabs to spaces…

**Comment by roeslpa** [comment]
I changed it back, but some other format changes were automatically done by my IntelliJ, I think we use the eclipse format, right?

**Comment by audax** [comment]
The more important policy is to not commit any formatting-only changes if not absolutely needed.
I don't want to be pedantic though, so it's fine by me this time.

ack

**Comment by jan-schreib** [comment]
Travis is failing. You branch is not up to date.

**Comment by roeslpa** [comment]
@jan-schreib both problems are solved.

**Pull request merged**
