### PR TITLE
Added prefixes to hashCode

### PR DESCRIPTION
**Pull request by roeslpa**
Resolves issue in #447

### CODE REVIEW

**Comment by audax** [comment]
@julianseeger please confirm the fix

**Comment by julianseeger** [comment]
It probably fixes the test (I'll check that later) but from an ideological point of view, after adding a prefix to an identity it is still the same identity just with some additional meta information isn't it?
When adding prefixes to an identity changes it's hash, you can't rely on an identity in identity or hash based structures like HashMaps etc. even though most information is immutable (like the private key). Maybe it's just personal opinion but I don't think so.
Other informations like email and phone don't change the hashCode and maybe the alias shouldn't chage it, too.

**Comment by roeslpa** [comment]
From my point of view either all information of the identity should affect the hash or only the key pair. The glossary says key pair and nickname=alias define an identity. I cannot see a reason for attaching information to the identity directly but pretending as if they are not part of it. 
As far as I know originally contact information should not be part of the identity but "module-data". Since mail and phone number are not essential for our current goal and prefixes do not affect the identity, I would change the test instead of the hash calculation. And I would propose to outsource all mutable data to another class because there should be a way to compare attached data as well..

**Comment by julianseeger** [comment]
The quick fix would probably be to extend the ConfigHashCodeTest to `ignoreProperty('prefixes')` but as we are already that deep in the design, the long version:

> From my point of view either all information of the identity should affect the hash or only the key pair. The glossary says key pair and nickname=alias define an identity.

Ack. Even though the second part suggests that the hash should be build from keypair AND alias, the latter is mutable afaik so should not be part of the hash imho.

> As far as I know originally contact information should not be part of the identity but "module-data". Since mail and phone number are not essential for our current goal and prefixes do not affect the identity, I would change the test instead of the hash calculation. And I would propose to outsource all mutable data to another class because there should be a way to compare attached data as well..

Is that neccessary? If all immutable data / properties affect the hashcode and all mutable data affect the equals method (in addition to the immutable data / hash) then all required conditions hold:
 * hashCode is immutable
 * if `a.hashCode() == b.hashCode()` now, and neither a nor b are modified then `a.hashCode() == b.hashCode()` in the future
 * if a.equals(b) then a.hashCode() == b.hashCode()
 * of course, both are reflexive, symmetric, transitive and consistent
 * as a result, `a.equals(b)` is `a way to compare attached data as well` (quote from you)

So if I didn't miss something, this could be a way to achieve everything without extracting mutable data to another class. (compare attached/mutable data, have working `equals` and `hashCode` implementations and use the class for hashing because hashes are immutable.

[SO answer to equals/hashCode](http://stackoverflow.com/questions/27581/what-issues-should-be-considered-when-overriding-equals-and-hashcode-in-java)

**Comment by roeslpa** [comment]
Ack. I will apply this to the code.

**Comment by roeslpa** [comment]
done.

**Comment by julianseeger** [comment]
#445

**Comment by julianseeger** [comment]
looks good and works for me

**Pull request merged**
