### PR TITLE
Issue298 part2 port config component to ackack

### LINKED ISSUE #298: Port Config and Contact components to ackack
@f-porter wants to look into how to use ackack using #252 (which references all example pull requests) and ask @Gottox open questions if needed. This is because we need to solve the problem how to get / change resources like settings and contacts -- which is described in #185.

A pull request to propose how to solve the problem described above is the next step.

### PR DESCRIPTION
**Pull request by f-porter**
Depends on PR #305.

Closes #298.

### CODE REVIEW

**Comment by f-porter** [comment]
Again a time out error in travis...

**Comment by L-Henke** [comment]
What is the purpose of the ```replace``` method? Wouldn't it replace the object with the same object? I would an replace method like this ```replace(oldObject, newObject)```, your ```replace(object)``` is more like an ```update(object)```.

**Comment by thechauffeur** [comment]
#305 is merged now please update this PR accordingly.

**Comment by f-porter** [comment]
@L-Henke, you are right. From this view the ```replace``` method is like an ```update``` method. I will change the name to prevent misinterpretation.

**Pull request merged**
