### PR TITLE
Added list of prefixes to Identity

### PR DESCRIPTION
**Pull request by L-Henke**
Added list of prefixes to Identity as discussed with @audax.

### CODE REVIEW

**Comment by roeslpa** [comment]
Ack :+1:

**Comment by julianseeger** [comment]
no Ack.
The current master produces a 
`Property "prefixes" is not significant!`
from `de.qabel.core.ExtendedHashCodeMethodTester.testHashCodeMethod(ExtendedHashCodeMethodTester.java:92)`

can anyone confirm this?

**Comment by roeslpa** [comment]
Unfortunately I can confirm this.

**Comment by audax** [comment]
Should I revert this or can someone provide a fix? Looks like the prefixes are just missing in the hash method.

**Comment by roeslpa** [comment]
I can provide a fix.

**Pull request merged**
