### PR TITLE
ec25519 native build

### PR DESCRIPTION
**Pull request by jan-schreib**
I was assigned in #325 since I don't have any rights in @moritz4004 fork, I started to work in my own.

### CODE REVIEW

**Comment by jan-schreib** [comment]
This fixes the gradle issue that happened in #325, but right I can't travis command to use python3.4 in here. @audax do you have an idea on this?
On my test machines the lib gets build and all tests are passing.

**Comment by audax** [comment]
As soon as we fix #386, it should work. I am currently working on it and just have to fix up stuff to make it ready for a PR.

**Comment by jasinai** [comment]
@jan-schreib your merge was wrong, I think. With [this modified commit](https://github.com/jasinai/qabel-core/commit/6ff96b5c9f026cfdcedeb4736085e59f140a2dc8) it works as you can see [here](https://travis-ci.org/jasinai/qabel-core) (The getCredentials test fails, because I tested it in my repository. :wink: )

**Comment by jan-schreib** [comment]
closed in favor of #407

**Pull request closed without merging**
