### PR TITLE
implemented resetPassword for AccountingHTTP Qabel/qabel-desktop#55

### PR DESCRIPTION
**Pull request by julianseeger**
Client implementation of /api/v0/auth/password/reset/

### CODE REVIEW

**Comment by jan-schreib** [comment]
There is no check if the email is valid. That checks are also missing in the Account classes. Maybe we need to look further into this.

**Comment by julianseeger** [comment]
for the password reset, a validation is done server-side

**Comment by jan-schreib** [comment]
Thats one request (and answer) per invalid mail. I think that could and should be avoided. The server should check nonetheless. But maybe I'm thinking to much about saving traffic right now.

**Comment by audax** [comment]
The first check should happen in the desktop and android client, not in the qabel-core. In the GUI we can enforce a properly formatted email address for which both GUIs we use have decent tools available for.

Checking emails without sending an email is futile anyway.

ack

**Pull request merged**
