### PR TITLE
Added alias field to Contact

### PR DESCRIPTION
**Pull request by L-Henke**

### CODE REVIEW

**Comment by jasinai** [comment]
Can you also adapt qabel-helloworld-module ?

**Comment by L-Henke** [comment]
Done: https://github.com/Qabel/qabel-helloworld-module/pull/22

**Comment by jasinai** [comment]
Looks good and the tests also passed.
I think, we should also update https://qabel.github.io/docs/Qabel-Client-Contact-Drop-Messages/ . The `keys` are also not up-to-date.

**Comment by thechauffeur** [comment]
@jasinai yes you are right. @L-Henke should have not only done a PR for `qabel-helloworld-module` but also for the documentation. Since is has not been done and there is also no issue for that -- which is bad practice BTW -- see Qabel/qabel.github.io#97.

**Pull request merged**
