### PR TITLE
Sets the If-Modified-Since header manually

### PR DESCRIPTION
**Pull request by jasinai**
The drop server didn't understand the date format, which was
generated by java. So we generate our own date format with
english locale and set the If-Modified-Since header.

### CODE REVIEW

**Comment by thechauffeur** [comment]
@jasinai some tests related to the given patch set fail so I hesitate to merge this. Is this needed for the showcase tomorrow? Do we need this in `qabel-core` `master` or the Android test branch?

**Comment by thechauffeur** [comment]
I somehow read that this would be merged into `master`. Sorry about that.

Since this is about `android-workaround` I let @L-Henke decide.

**Comment by jasinai** [comment]
For the time being we only need this in the android test branch.
I will fix the import in the DropHTTP tests.
I can fix the module manager tests in another PR, if we want to keep the new constructor of the module manager.

**Comment by thechauffeur** [comment]
@jasinai sorry I thought you wanted to merge this into `master`. Forget what I said. You have to discuss this with @L-Henke not with me.

**Comment by thechauffeur** [comment]
@L-Henke told me that he does not need this PR anymore.

**Pull request closed without merging**
