### PR TITLE
[micro-optimization] Static StorageHTTP methods

### PR DESCRIPTION
**Pull request by aBothe**
See commit message.

### CODE REVIEW

**Comment by jasinai** [comment]
> Is there any API doc that states StorageHTTP to be instantiated/non-static?

I don't think so.

Looks good. Can be merged.

**Comment by cburkert** [comment]
Note that the API changes I made in #241 make it necessary to instantiate StorageHTTP, because it will contain connection state information.

**Comment by aBothe** [comment]
Sure, already presumed that this pr affected mine :)

**Comment by thechauffeur** [comment]
We decided that this PR will be closed in favor of #241. Review this instead.

**Pull request closed without merging**
