### PR TITLE
Fixes #303

### LINKED ISSUE #303: Define how to deal with dependent method calls
We sometimes have dependent method calls. (e.g. one method have to be called after another).

E.g: ```registerSender``` has to be called to complete the serialization of a Drop message:
https://github.com/Qabel/qabel-core/blob/master/src/main/java/de/qabel/core/drop/DropMessage.java#L74

And:
The serialize and deserialize of the ```AbstractBinaryDropMessage``` are related to which constructor has been used ```byte[] binaryMessage``` or ```DropMessage<?> dropMessage```. These methods are not testing if the current call is actually possible.

How should be deal with that kind of dependent methods. Is a Javadoc comment enough, or is there maybe a better way to do this? Should these methods check if their call is valid in the current context?

### PR DESCRIPTION
**Pull request by thechauffeur**
Define how to deal with depended methods calls.

### CODE REVIEW

**Comment by thechauffeur** [comment]
Fixes #303

**Comment by L-Henke** [comment]
:+1:

**Comment by jan-schreib** [comment]
The name of the method has to be ```initialize()```? IIRC @L-Henke named one method ```init()``` which was renamed to ```connect()``` eventually. Don't get me wrong, I'm fine with the longer name. I'm just wondering because we had ```init()``` in a pullrequest about 4 hours ago.

**Comment by L-Henke** [comment]
E.g. means it's just an example.

**Comment by jan-schreib** [comment]
Misinterpreted the 'E.g.' there. :+1:

**Pull request merged**
